[package]
name = "mywm"
version = "0.1.0"
edition = "2021"
authors = ["Chris Dawkins"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penrose = "0.2"
simplelog = "0.8"
clap = { version = "3.1", features = ["derive", "env"] }
