[package]
name = "MYWM"
version = "0.1.0"
edition = "2018"
authors = ["Chris Dawkins"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penrose = "0.2"
simplelog = "0.8"
